import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { spawn } from "child_process";

// Configurable models via environment variables or default fallbacks
const MODEL_GEN_A = process.env.ENSEMBLE_GEN_A || "qwen3.6:27b-mlx";
const MODEL_GEN_B = process.env.ENSEMBLE_GEN_B || "gemma4:26b-mlx";
const MODEL_JUDGE = process.env.ENSEMBLE_JUDGE || "gemini-3.1-pro-preview";

// Helper to query local Ollama HTTP endpoints
async function queryOllama(model: string, systemPrompt: string, userPrompt: string): Promise<string> {
  const response = await fetch("http://localhost:11434/v1/chat/completions", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: model,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.7
    })
  });

  if (!response.ok) {
    throw new Error(`Ollama fetch failed for ${model}: ${response.statusText}`);
  }

  const json = await response.json() as any;
  return json.choices[0].message.content;
}

// Helper to spawn the local Gemini CLI as the ultimate Judge
function runGeminiJudge(prompt: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const child = spawn("gemini", ["-p", prompt]);
    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (data) => { stdout += data.toString(); });
    child.stderr.on("data", (data) => { stderr += data.toString(); });

    child.on("close", (code) => {
      if (code === 0) {
        // Clean up stderr fallback messages if any bleed into stdout
        const cleanOutput = stdout
          .replace("Ripgrep is not available. Falling back to GrepTool.\n", "")
          .trim();
        resolve(cleanOutput);
      } else {
        reject(new Error(`Gemini CLI failed with code ${code}: ${stderr}`));
      }
    });
  });
}

export default function ensembleExtension(pi: ExtensionAPI) {
  // System prompt for generators
  const systemPrompt = "You are an expert technical advisor. Provide a highly detailed, technically rigorous, and accurate answer to the user's question. Focus on correctness and avoid fluff.";

  const runPipeline = async (
    prompt: string, 
    strategy: "synthesize" | "best_of_n", 
    notify: (msg: string) => void
  ): Promise<string> => {
    notify(`Dispatching requests to local generators (${MODEL_GEN_A} & ${MODEL_GEN_B}) in parallel...`);
    
    // 1. Fire parallel calls to Ollama
    const [genAResponse, genBResponse] = await Promise.all([
      queryOllama(MODEL_GEN_A, systemPrompt, prompt).catch(e => `[Error ${MODEL_GEN_A}]: ${e.message}`),
      queryOllama(MODEL_GEN_B, systemPrompt, prompt).catch(e => `[Error ${MODEL_GEN_B}]: ${e.message}`)
    ]);

    notify(`Generators complete. Formatting arbitration context using strategy: '${strategy}'...`);

    // 2. Format the synthesis/judging prompt for the Judge based on the selected strategy
    let judgePrompt = "";
    if (strategy === "best_of_n") {
      judgePrompt = `
You are the Supreme Judge in a Mixture-of-Agents ensemble. 
Below is a user's original request along with answers generated by two distinct expert models.

Your task:
1. Critically evaluate both expert responses for accuracy, technical depth, correctness, and potential hallucinations.
2. Select the single superior response.
3. Return that chosen response absolutely verbatim. Do NOT modify the code, syntax, or phrasing of the winning response. 
4. Output ONLY the verbatim winning response, without any introductory or concluding remarks (do not say "Model A is better" or "Here is the winning response").

[Original User Prompt]:
${prompt}

---

[Expert Response A (${MODEL_GEN_A})]:
${genAResponse}

---

[Expert Response B (${MODEL_GEN_B})]:
${genBResponse}

---

Provide the verbatim winning response below:
`;
    } else {
      // Default: synthesize
      judgePrompt = `
You are the Supreme Judge in a Mixture-of-Agents ensemble. 
Below is a user's original request along with answers generated by two distinct expert models.

Your task:
1. Critically evaluate both responses for accuracy, omissions, and hallucinations.
2. Synthesize the absolute best parts of both answers.
3. Resolve any contradictions based on ground truth and standard engineering patterns.
4. Output a single, perfectly unified, professional, and definitive master answer. Do not output multiple sections of "Model A said X, Model B said Y" unless helpful for contrasting trade-offs. Present the final output as a single cohesive response.

[Original User Prompt]:
${prompt}

---

[Expert Response A (${MODEL_GEN_A})]:
${genAResponse}

---

[Expert Response B (${MODEL_GEN_B})]:
${genBResponse}

---

Provide your final master synthesis below.
`;
    }

    notify(`Invoking ${MODEL_JUDGE} for final decision...`);

    // 3. Execute the Gemini CLI Judge
    return await runGeminiJudge(judgePrompt);
  };

  // 1. Register LLM Tool
  pi.registerTool({
    name: "ask_ensemble",
    label: "Ask MoA Ensemble",
    description: "Queries a Mixture-of-Agents ensemble of local and cloud models. Concurrently runs local generator models, then passes both responses to Gemini to judge and select/synthesize the definitive answer.",
    parameters: Type.Object({
      prompt: Type.String({ description: "The complex question or challenge to resolve." }),
      strategy: Type.Optional(Type.Union([
        Type.Literal("synthesize"),
        Type.Literal("best_of_n")
      ], { 
        description: "The arbitration strategy. 'synthesize' merges responses; 'best_of_n' returns the winning model's response completely verbatim.",
        default: "synthesize" 
      }))
    }),
    async execute(_id, params) {
      const strategy = params.strategy || "synthesize";
      try {
        const result = await runPipeline(params.prompt, strategy, (msg) => console.log(`[Ensemble]: ${msg}`));
        return {
          content: [
            {
              type: "text",
              text: result
            }
          ]
        };
      } catch (error: any) {
        return {
          content: [
            {
              type: "text",
              text: `Ensemble Pipeline Error: ${error.message}`
            }
          ],
          isError: true
        };
      }
    }
  });

  // 2. Register Slash Command
  pi.registerCommand("ensemble", {
    description: "Ask a question to the local/cloud ensemble pipeline directly. Options: --strategy [synthesize|best_of_n]",
    handler: async (args: string, ctx) => {
      let prompt = (args || "").trim();
      let strategy: "synthesize" | "best_of_n" = "synthesize";

      // Parse --strategy flag if present
      if (prompt.includes("--strategy")) {
        const match = prompt.match(/--strategy\s+(\S+)/);
        if (match) {
          const val = match[1].toLowerCase();
          if (val === "best_of_n" || val === "synthesize") {
            strategy = val as any;
          }
          prompt = prompt.replace(/--strategy\s+\S+/, "").trim();
        }
      }

      // If no prompt was provided, ask the user interactively
      if (!prompt) {
        const answer = await ctx.ui.editor("What is your complex question for the ensemble?");
        prompt = (answer || "").trim();
        if (!prompt) return;

        // Ask for strategy choice interactively
        const confirmBestOfN = await ctx.ui.confirm("Do you want to use 'best_of_n' strategy (returns winning response verbatim)? No defaults to 'synthesize'.");
        strategy = confirmBestOfN ? "best_of_n" : "synthesize";
      }

      ctx.ui.notify(`Initializing Ensemble Pipeline (${strategy} mode)...`);
      try {
        const result = await runPipeline(prompt, strategy, (msg) => ctx.ui.notify(msg));
        ctx.ui.print(`\n=== 🌟 Ensemble Master Answer (${strategy}) ===\n\n${result}\n`);
      } catch (error: any) {
        ctx.ui.print(`\n❌ Error: ${error.message}\n`);
      }
    }
  });
}
